[workspace]
members = ["solana-nostd-entrypoint", "example-program", "system", "token"]
resolver = "2"


[workspace.dependencies]
solana-nostd-entrypoint = { path = "./solana-nostd-entrypoint" }
peregrine-alloc = { path = "./peregrine-alloc" }
solana-program = "1.18"
